namespace WeatherApp.Models
{
    public class LocationGuessModel
    {

        public string Name { get; set; }
        public  LocalNames? localNames { get; set; }
        public Coord coord { get; set; }
        public double lon { get; set; }
        public double lat { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
    }
    public class Coord
    {
        public double lon { get; set; }
        public double lat { get; set; }
    }
    public class LocalNames
    {
        public string Fo { get; set; }
        public string Jv { get; set; }
        public string Ba { get; set; }
        public string Cy { get; set; }
        public string De { get; set; }
        public string La { get; set; }
        public string Da { get; set; }
        public string Sm { get; set; }
        public string Br { get; set; }
        public string Mt { get; set; }
        public string Lg { get; set; }
        public string Sr { get; set; }
        public string Pl { get; set; }
        public string Mn { get; set; }
        public string Am { get; set; }
        public string Th { get; set; }
        public string Vo { get; set; }
        public string Sw { get; set; }
        public string Kn { get; set; }
        public string Id { get; set; }
        public string Ka { get; set; }
        public string Tg { get; set; }
        public string Sv { get; set; }
        public string Zh { get; set; }
        public string Bs { get; set; }
        public string Ja { get; set; }
        public string Fa { get; set; }
        public string My { get; set; }
        public string St { get; set; }
        public string Sk { get; set; }
        public string Pt { get; set; }
        public string Se { get; set; }
        public string Kg { get; set; }
        public string Wa { get; set; }
        public string Sh { get; set; }
        public string Mi { get; set; }
        public string Cu { get; set; }
        public string Kv { get; set; }
        public string Ku { get; set; }
        public string Ab { get; set; }
        public string Ascii { get; set; }
        public string Ia { get; set; }
        public string Mg { get; set; }
        public string Cv { get; set; }
        public string Sq { get; set; }
        public string Sl { get; set; }
        public string It { get; set; }
        public string Fi { get; set; }
        public string Ln { get; set; }
        public string Ch { get; set; }
        public string Cs { get; set; }
        public string An { get; set; }
        public string Ss { get; set; }
        public string Tl { get; set; }
        public string Eu { get; set; }
        public string Ta { get; set; }
        public string Nb { get; set; }
        public string Kw { get; set; }
        public string Ug { get; set; }
        public string Gv { get; set; }
        public string Hi { get; set; }
        public string Yo { get; set; }
        public string Fy { get; set; }
        public string Ko { get; set; }
        public string Dv { get; set; }
        public string Co { get; set; }
        public string Za { get; set; }
        public string Gd { get; set; }
        public string Ar { get; set; }
        public string Ay { get; set; }
        public string Et { get; set; }
        public string En { get; set; }
        public string Ms { get; set; }
        public string Kl { get; set; }
        public string Bg { get; set; }
        public string Tr { get; set; }
        public string Ht { get; set; }
        public string Zu { get; set; }
        public string Mr { get; set; }
        public string Dz { get; set; }
        public string Ca { get; set; }
        public string Su { get; set; }
        public string Ie { get; set; }
        public string Nn { get; set; }
        public string Vi { get; set; }
        public string Ur { get; set; }
        public string Is { get; set; }
        public string Ak { get; set; }
        public string Az { get; set; }
        public string Ru { get; set; }
        public string Es { get; set; }
        public string Hu { get; set; }
        public string Af { get; set; }
        public string Bi { get; set; }
        public string Bn { get; set; }
        public string Nl { get; set; }
        public string Ty { get; set; }
        public string El { get; set; }
        public string Yi { get; set; }
        public string Bo { get; set; }
        public string Io { get; set; }
        public string Qu { get; set; }
        public string Fr { get; set; }
        public string Be { get; set; }
        public string Tt { get; set; }
        public string Iu { get; set; }
        public string Os { get; set; }
        public string Ml { get; set; }
        public string Av { get; set; }
        public string Lt { get; set; }
        public string Hy { get; set; }
        public string Hr { get; set; }
        public string Ps { get; set; }
        public string Ky { get; set; }
        public string Na { get; set; }
        public string Gn { get; set; }
        public string Uz { get; set; }
        public string Sg { get; set; }
        public string So { get; set; }
        public string Wo { get; set; }
        public string FeatureName { get; set; }
        public string Gl { get; set; }
        public string Sc { get; set; }
        public string Li { get; set; }
        public string Te { get; set; }
        public string No { get; set; }
        public string Mk { get; set; }
        public string Uk { get; set; }
        public string Oc { get; set; }
        public string Ro { get; set; }
        public string He { get; set; }
        public string Lv { get; set; }
        public string Eo { get; set; }
        public string Tk { get; set; }
        public string Ce { get; set; }
        public string Ga { get; set; }
        public string Kk { get; set; }
    }
}
